# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 5.2.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#
# http://www.appveyor.com/docs/installed-software
# Visual Studio 2015 - Visual Studio Community 2015 RC with Visual Studio 2015 SDK RC are installed on a separate build worker 
# image called Visual Studio 2015 RC. You can select build worker image in "OS" dropdown on Environment tab of project settings 
# or if you use appveyor.yml add that line:
os: Visual Studio 2015 RC

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: false
  file: AssemblyInfo.*
  assembly_version: "5.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  project: VsExt.AutoShelve\VsExt.AutoShelve.csproj   # path to Visual Studio solution or project
  # MSBuild verbosity level quiet|minimal|normal|detailed
  verbosity: minimal


# scripts to run before build
before_build: rd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Amazon Web Services LLC" /s /q
#  - nuget restore
#  - rd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Amazon Web Services LLC" /s /q

# scripts to run after build
#after_build:

# to run your custom scripts instead of automatic MSBuild
#build_script:

# to disable automatic builds
#build: off

test: off
#  assemblies: .UnitTests.dll

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file
  - path: .\VsExt.AutoShelve\bin\$(configuration)\VsExt.AutoShelve.vsix
    name: VsExt.AutoShelve.vsix
  # pushing a single file with environment variable in path and "Deployment name" specified
  # zips all the bin\release folder as output.zip
  #- path: .\bin\$(configuration)
  #  name: Output.zip

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
# to disable deployment set to off
deploy: off 
