//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsExt.AutoShelve {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsExt.AutoShelve.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Auto Shelve.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a shelveset for the latest version of all pending changes, automatically.  Pending changes from the local TFS workspaces will be shelved to the TFS Server every &quot;x&quot; number of minutes when solutions are opened..
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon _400 {
            get {
                object obj = ResourceManager.GetObject("400", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto {0}.
        /// </summary>
        internal static string DefaultShelvetsetName {
            get {
                return ResourceManager.GetString("DefaultShelvetsetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} encountered an error..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Connection failed.  Fix your connection and source control bindings then restart TFS Auto Shelve..
        /// </summary>
        internal static string ErrorNotConnected {
            get {
                return ResourceManager.GetString("ErrorNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Auto Shelve.
        /// </summary>
        internal static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Running).
        /// </summary>
        internal static string MenuTextRunning {
            get {
                return ResourceManager.GetString("MenuTextRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Stopped).
        /// </summary>
        internal static string MenuTextStopped {
            get {
                return ResourceManager.GetString("MenuTextStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than 0..
        /// </summary>
        internal static string PositiveNumberError {
            get {
                return ResourceManager.GetString("PositiveNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - {0} Settings.
        /// </summary>
        internal static string SettingsErrorTitle {
            get {
                return ResourceManager.GetString("SettingsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelved by {0}. {1} items.
        /// </summary>
        internal static string ShelvesetComment {
            get {
                return ResourceManager.GetString("ShelvesetComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shelved {0} pending changes to Shelveset Name: {1}.
        /// </summary>
        internal static string ShelvesetSuccess {
            get {
                return ResourceManager.GetString("ShelvesetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Maximum Shelvesets: {0} | Deleted: {1}.
        /// </summary>
        internal static string ShelvesetSucessPurged {
            get {
                return ResourceManager.GetString("ShelvesetSucessPurged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} paused while debugging..
        /// </summary>
        internal static string StatePaused {
            get {
                return ResourceManager.GetString("StatePaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is running..
        /// </summary>
        internal static string StateRunning {
            get {
                return ResourceManager.GetString("StateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is stopped..
        /// </summary>
        internal static string StateStopped {
            get {
                return ResourceManager.GetString("StateStopped", resourceCulture);
            }
        }
    }
}
